In [1]:
# Before we do anything, we need to import NumPy
import numpy as np

In [2]:
movie_ratings = np.array([[63.0, 54.0, 70.0, 50.0],
                          [94.0, 85.0, 89.0, 95.0],
                          [64.0, 90.0, 73.0, 85.0]])

Some fans prefer to have the movies rated on a five star scale, so we can use NumPy to easily divide each element by 20.

In [3]:
movie_ratings_stars = movie_ratings / 20

Now let's say the ratings are always in the same order (Lorie, Marty, Tori, Kurtz) if we wanted to create an array that only had Tori's ratings, we could select that from our movie_ratings array.

In [4]:
tori_ratings = movie_ratings[:, 2]
tori_ratings

array([ 70.,  89.,  73.])

Now, say we find that we have very similar taste to Marty, so we only want to see movies that he gives a good rating to, we can use logic to select those movies.

Let's select all of Marty's ratings that are over 80:

In [11]:
marty_ratings = movie_ratings[:, 1]
marty_ratings

array([ 54.,  85.,  90.])

In [8]:
marty_ratings[marty_ratings > 80]

array([ 85.,  90.])

In [9]:
marty_ratings

array([ 54.,  85.,  90.])

### Creating an Array from a CSV
Typically, you won't be entering data directly into an array. Instead, you'll be importing the data from somewhere else.

We're able to transform CSV (comma-separated values) files into arrays using the np.genfromtxt() function:

Consider the following CSV, sample.csv,
```
34,9,12,11,7
```
We can import this into a NumPy array using the following code:
```
csv_array = np.genfromtxt('sample.csv', delimiter=',')
```
Note that in this case, our file sample.csv has values separated by commas, so we use delimiter=',', but sometimes you'll find files with other delimiters, the most common being tabs or colons.

Once imported, this CSV will create the array
```python
>>> csv_array
array([34, 9, 12, 11, 7])
```

### Two-Dimensional Arrays

two-dimensional array:
```python
np.array([[92, 94, 88, 91, 87], 
          [79, 100, 86, 93, 91],
          [87, 85, 72, 90, 92]])
```

As we mentioned, a two-dimensional array is a list of lists where each list has the same number of elements. Here are some examples that are not two-dimensional arrays.

This code will run but it will not create a two-dimensional array because the lists have different numbers of elements:
```python
np.array([[29, 49,  6], 
          [77,  1]])
```


### Selecting Elements from a 2-D Array
Selecting elements from a 2-d array is very similar to selecting them from a 1-d array, we just have two indices to select from. The syntax for selecting from a 2-d array is `a[row,column]` where a is the array.
<img src="images/NumPy_Array.svg" style="width:650px;height:400px;">

In [13]:
a = np.array([[32, 15, 6, 9, 14], 
              [12, 10, 5, 23, 1],
              [2, 16, 13, 40, 37]])
a[2,1]

16

In [15]:
# selects the first column
a[:,0]

array([32, 12,  2])

In [16]:
# selects the second row
a[1,:]

array([12, 10,  5, 23,  1])

In [17]:
# selects the first three elements of the first row
a[0,0:3]

array([32, 15,  6])

### Logical Operations with Arrays
Another useful thing that arrays can do is perform element-wise logical operations. For instance, suppose we want to know how many elements in an array are greater than 5. We can easily write some code that checks to see whether this statement evaluates to True for each item in the array, without having to use a for loop :


In [18]:
a = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
a > 5

array([ True, False, False, False, False, False,  True,  True,  True,  True], dtype=bool)

We can then use logical operators to evaluate and select items based on certain criteria. To select all elements from the previous array that are greater than 5, we'd write the following:

In [19]:
a[a > 5]

array([10,  9,  8,  9,  7])